apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment          # This can stay static or match app name if needed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app                  # Must match the template labels
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container    # This will be replaced by the script dynamically
          image: 73333/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  type: NodePort   # <--- Changed from ClusterIP to NodePort
  selector:
    app: my-app
  ports:
    - port: 80          # Service port (inside cluster)
      targetPort: 8000    # Pod container port (from your app)
      nodePort: 30080   # <--- Exposed port on minikube (range: 30000–32767)
